name: nutrition
description: "A new Flutter project for G10"

version: 1.0.0+1

environment:
  sdk: ">=3.4.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Design
  cupertino_icons: ^1.0.6
  toastification: ^2.1.0
  l: ^4.0.2
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.10+1

  # State management
  flutter_riverpod: ^2.5.1

  # Network
  dio: ^5.5.0+1

  # Storage
  flutter_secure_storage: ^9.2.2
  connectivity_plus: ^6.0.4
  shared_preferences: ^2.3.1

  # Navigation
  go_router: ^14.2.3
  device_preview: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
  #   - images/a_dot_ham.jpeg

  fonts:
     - family: Poppins
       fonts:
         - asset: assets/fonts/Poppins-Black.ttf
         - asset: assets/fonts/Poppins-BlackItalic.ttf
         - asset: assets/fonts/Poppins-Bold.ttf
         - asset: assets/fonts/Poppins-BoldItalic.ttf
         - asset: assets/fonts/Poppins-ExtraBold.ttf
         - asset: assets/fonts/Poppins-ExtraBoldItalic.ttf
         - asset: assets/fonts/Poppins-ExtraLight.ttf
         - asset: assets/fonts/Poppins-ExtraLightItalic.ttf
         - asset: assets/fonts/Poppins-Italic.ttf
         - asset: assets/fonts/Poppins-Light.ttf
         - asset: assets/fonts/Poppins-LightItalic.ttf
         - asset: assets/fonts/Poppins-Medium.ttf
         - asset: assets/fonts/Poppins-MediumItalic.ttf
         - asset: assets/fonts/Poppins-Regular.ttf
         - asset: assets/fonts/Poppins-SemiBold.ttf
         - asset: assets/fonts/Poppins-SemiBoldItalic.ttf
         - asset: assets/fonts/Poppins-Thin.ttf
         - asset: assets/fonts/Poppins-ThinItalic.ttf
           style: italic
