name: nutrition
description: "A new Flutter project for G10"

version: 1.0.0+1

environment:
  sdk: ">=3.4.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Design
  cupertino_icons: ^1.0.6
  toastification: ^2.1.0
  l: ^4.0.2
#  sizer: ^2.0.15

  # State management
  flutter_riverpod: ^2.5.1

  # Network
  dio: ^5.5.0+1

  # Storage
  flutter_secure_storage: ^9.2.2
  connectivity_plus: ^6.0.4
  shared_preferences: ^2.3.1
  flutter_svg: ^2.0.10+1
  flutter_screenutil: ^5.9.3
  device_preview: ^1.2.0
  go_router: ^14.2.3
  image_picker: ^1.1.2
  zoom_tap_animation: ^1.1.0
  file_picker: ^8.0.0+1
  pinput: ^5.0.0
  email_otp: ^2.1.2
  pin_code_fields: ^8.0.1

  # Localization
  flutter_localizations:
    sdk: flutter
  intl: any

  # rate my app
  flutter_rating_bar: ^4.0.1
  share_plus: ^7.2.2

  # shimmer
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/

  fonts:
     - family: Poppins
       fonts:
         - asset: assets/fonts/Poppins-Black.ttf
           weight: 900
         - asset: assets/fonts/Poppins-BlackItalic.ttf
           weight: 900
           style: italic

         - asset: assets/fonts/Poppins-ExtraBold.ttf
           weight: 800
         - asset: assets/fonts/Poppins-ExtraBoldItalic.ttf
           weight: 800
           style: italic

         - asset: assets/fonts/Poppins-Bold.ttf
           weight: 700
         - asset: assets/fonts/Poppins-BoldItalic.ttf
           weight: 700
           style: italic

         - asset: assets/fonts/Poppins-SemiBold.ttf
           weight: 600
         - asset: assets/fonts/Poppins-SemiBoldItalic.ttf
           weight: 600
           style: italic

         - asset: assets/fonts/Poppins-Medium.ttf
           weight: 500
         - asset: assets/fonts/Poppins-MediumItalic.ttf
           weight: 500
           style: italic

         - asset: assets/fonts/Poppins-Regular.ttf
           weight: 400

         - asset: assets/fonts/Poppins-Light.ttf
           weight: 300
         - asset: assets/fonts/Poppins-LightItalic.ttf
           weight: 300
           style: italic

         - asset: assets/fonts/Poppins-ExtraLight.ttf
           weight: 200
         - asset: assets/fonts/Poppins-ExtraLightItalic.ttf
           weight: 200
           style: italic

         - asset: assets/fonts/Poppins-Thin.ttf
           weight: 100
         - asset: assets/fonts/Poppins-ThinItalic.ttf
           weight: 100
           style: italic

         - asset: assets/fonts/Poppins-Italic.ttf
